apiVersion: apps/v1 #指定使用API-V1版本
kind: Deployment #指定類型為Deployment
metadata: #定義資源
  name: nginx-deployment #定義Deployment的名稱
  annotations: #添加註解，方便部署
        kubernetes.io/change-cause: UP-123
spec: #描述規格
  selector: #標籤選擇器
    matchLabels: #創建的Pod須符合的標籤
      app: nginx #標籤名為nginx
  replicas: 3 # tells deployment to run 3 pods matching the template
  template: #配置POD
    metadata: #定義資源
      labels: #使用的標籤
        app: nginx #使用nginx標籤
    spec: #描述規格
      containers: #定義容器
      - name: nginx #容器名為
        image:  rv88/web-8000:v1 #使用的image
        ports: #設定POD的端口
        - containerPort: 8000
