piVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: blue.demo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: blue-nginx-service
          servicePort: 8000
  - host: green.demo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: green-nginx-service
          servicePort: 8000
